spring: # 向Eureka注册服务时，需要安全认证，包括第三方服务注册也需要
  #profiles: dev-8091
  security:
      user:
        name: reg-eureka
        password: reg-eureka
        
server:
  port: 8091

eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
    enable-self-preservation: false #设置为false表示关闭保护模式
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://reg-eureka:reg-eureka@eureka1:8091/eureka,http://reg-eureka:reg-eureka@eureka2:8092/eureka,http://reg-eureka:reg-eureka@eureka3:8093/eureka
  instance:
    hostname: eureka1
