server:
  port: 80

feign:
  hystrix:
    enabled: true
    compression:
      request:
        enabled: true
        mime-types:   # 可以被压缩的类型
          - text/xml
          - application/xml
          - application/json
        min-request-size: 2048  # 超过2048的字节进行压缩
      
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://reg-eureka:reg-eureka@eureka1:8091/eureka,http://reg-eureka:reg-eureka@eureka2:8092/eureka,http://reg-eureka:reg-eureka@eureka3:8093/eureka

logging:  # 记录日志
  level:
    com.test.springcloud.controller: DEBUG