package com.test.springcloud.dao;

import java.util.List;

import com.test.springcloud.entity.TUser;


public interface TUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    List<TUser> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUser record);
    
    
    
    List<TUser> selectAssocition();
    
    List<TUser> selectAssocition2();
    
    TUser selectIncludeJobs(Integer userId);
    
    /**
     * 	查询所有用户信息及体检报告信息
     * @param userId
     * @return
     */
    List<TUser> selectUserHealthReport();
    
    /**
     * 	查询所有用户信息、角色信息-嵌套结果
     * @param userId
     * @return
     */
    List<TUser> selectUserRolesInfo();
}